// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// DeleteWipeReader is a Reader for the DeleteWipe structure.
type DeleteWipeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteWipeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteWipeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewDeleteWipeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteWipeOK creates a DeleteWipeOK with default headers values
func NewDeleteWipeOK() *DeleteWipeOK {
	return &DeleteWipeOK{}
}

/*DeleteWipeOK handles this case with default header values.

success
*/
type DeleteWipeOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *DeleteWipeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteWipeDefault creates a DeleteWipeDefault with default headers values
func NewDeleteWipeDefault(code int) *DeleteWipeDefault {
	return &DeleteWipeDefault{
		_statusCode: code,
	}
}

/*DeleteWipeDefault handles this case with default header values.

error
*/
type DeleteWipeDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the delete wipe default response
func (o *DeleteWipeDefault) Code() int {
	return o._statusCode
}

func (o *DeleteWipeDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *DeleteWipeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
