// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteWipeParams creates a new DeleteWipeParams object
// with the default values initialized.
func NewDeleteWipeParams() *DeleteWipeParams {

	return &DeleteWipeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteWipeParamsWithTimeout creates a new DeleteWipeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteWipeParamsWithTimeout(timeout time.Duration) *DeleteWipeParams {

	return &DeleteWipeParams{

		timeout: timeout,
	}
}

// NewDeleteWipeParamsWithContext creates a new DeleteWipeParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteWipeParamsWithContext(ctx context.Context) *DeleteWipeParams {

	return &DeleteWipeParams{

		Context: ctx,
	}
}

// NewDeleteWipeParamsWithHTTPClient creates a new DeleteWipeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteWipeParamsWithHTTPClient(client *http.Client) *DeleteWipeParams {

	return &DeleteWipeParams{
		HTTPClient: client,
	}
}

/*DeleteWipeParams contains all the parameters to send to the API endpoint
for the delete wipe operation typically these are written to a http.Request
*/
type DeleteWipeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete wipe params
func (o *DeleteWipeParams) WithTimeout(timeout time.Duration) *DeleteWipeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete wipe params
func (o *DeleteWipeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete wipe params
func (o *DeleteWipeParams) WithContext(ctx context.Context) *DeleteWipeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete wipe params
func (o *DeleteWipeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete wipe params
func (o *DeleteWipeParams) WithHTTPClient(client *http.Client) *DeleteWipeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete wipe params
func (o *DeleteWipeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteWipeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
