// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// GetConnectedReader is a Reader for the GetConnected structure.
type GetConnectedReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConnectedReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetConnectedOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetConnectedDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetConnectedOK creates a GetConnectedOK with default headers values
func NewGetConnectedOK() *GetConnectedOK {
	return &GetConnectedOK{}
}

/*GetConnectedOK handles this case with default header values.

success
*/
type GetConnectedOK struct {
	Payload *GetConnectedOKBody
}

func (o *GetConnectedOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetConnectedOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetConnectedDefault creates a GetConnectedDefault with default headers values
func NewGetConnectedDefault(code int) *GetConnectedDefault {
	return &GetConnectedDefault{
		_statusCode: code,
	}
}

/*GetConnectedDefault handles this case with default header values.

error
*/
type GetConnectedDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the get connected default response
func (o *GetConnectedDefault) Code() int {
	return o._statusCode
}

func (o *GetConnectedDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *GetConnectedDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetConnectedOKBody get connected o k body
swagger:model GetConnectedOKBody
*/
type GetConnectedOKBody struct {

	// data
	Data bool `json:"data,omitempty"`
}

// Validate validates this get connected o k body
func (o *GetConnectedOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetConnectedOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetConnectedOKBody) UnmarshalBinary(b []byte) error {
	var res GetConnectedOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
