// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostCheckMessageSignatureReader is a Reader for the PostCheckMessageSignature structure.
type PostCheckMessageSignatureReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostCheckMessageSignatureReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostCheckMessageSignatureOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostCheckMessageSignatureDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostCheckMessageSignatureOK creates a PostCheckMessageSignatureOK with default headers values
func NewPostCheckMessageSignatureOK() *PostCheckMessageSignatureOK {
	return &PostCheckMessageSignatureOK{}
}

/*PostCheckMessageSignatureOK handles this case with default header values.

success
*/
type PostCheckMessageSignatureOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PostCheckMessageSignatureOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostCheckMessageSignatureDefault creates a PostCheckMessageSignatureDefault with default headers values
func NewPostCheckMessageSignatureDefault(code int) *PostCheckMessageSignatureDefault {
	return &PostCheckMessageSignatureDefault{
		_statusCode: code,
	}
}

/*PostCheckMessageSignatureDefault handles this case with default header values.

error
*/
type PostCheckMessageSignatureDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the post check message signature default response
func (o *PostCheckMessageSignatureDefault) Code() int {
	return o._statusCode
}

func (o *PostCheckMessageSignatureDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *PostCheckMessageSignatureDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
