// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostSetMnemonicReader is a Reader for the PostSetMnemonic structure.
type PostSetMnemonicReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSetMnemonicReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostSetMnemonicOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPostSetMnemonicConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostSetMnemonicOK creates a PostSetMnemonicOK with default headers values
func NewPostSetMnemonicOK() *PostSetMnemonicOK {
	return &PostSetMnemonicOK{}
}

/*PostSetMnemonicOK handles this case with default header values.

success
*/
type PostSetMnemonicOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PostSetMnemonicOK) Error() string {
	return fmt.Sprintf("[POST /setMnemonic][%d] postSetMnemonicOK  %+v", 200, o.Payload)
}

func (o *PostSetMnemonicOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostSetMnemonicConflict creates a PostSetMnemonicConflict with default headers values
func NewPostSetMnemonicConflict() *PostSetMnemonicConflict {
	return &PostSetMnemonicConflict{}
}

/*PostSetMnemonicConflict handles this case with default header values.

error
*/
type PostSetMnemonicConflict struct {
	Payload *models.HTTPErrorResponse
}

func (o *PostSetMnemonicConflict) Error() string {
	return fmt.Sprintf("[POST /setMnemonic][%d] postSetMnemonicConflict  %+v", 409, o.Payload)
}

func (o *PostSetMnemonicConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
