// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostSetPinCodeParams creates a new PostSetPinCodeParams object
// with the default values initialized.
func NewPostSetPinCodeParams() *PostSetPinCodeParams {

	return &PostSetPinCodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSetPinCodeParamsWithTimeout creates a new PostSetPinCodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSetPinCodeParamsWithTimeout(timeout time.Duration) *PostSetPinCodeParams {

	return &PostSetPinCodeParams{

		timeout: timeout,
	}
}

// NewPostSetPinCodeParamsWithContext creates a new PostSetPinCodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSetPinCodeParamsWithContext(ctx context.Context) *PostSetPinCodeParams {

	return &PostSetPinCodeParams{

		Context: ctx,
	}
}

// NewPostSetPinCodeParamsWithHTTPClient creates a new PostSetPinCodeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSetPinCodeParamsWithHTTPClient(client *http.Client) *PostSetPinCodeParams {

	return &PostSetPinCodeParams{
		HTTPClient: client,
	}
}

/*PostSetPinCodeParams contains all the parameters to send to the API endpoint
for the post set pin code operation typically these are written to a http.Request
*/
type PostSetPinCodeParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post set pin code params
func (o *PostSetPinCodeParams) WithTimeout(timeout time.Duration) *PostSetPinCodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post set pin code params
func (o *PostSetPinCodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post set pin code params
func (o *PostSetPinCodeParams) WithContext(ctx context.Context) *PostSetPinCodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post set pin code params
func (o *PostSetPinCodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post set pin code params
func (o *PostSetPinCodeParams) WithHTTPClient(client *http.Client) *PostSetPinCodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post set pin code params
func (o *PostSetPinCodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostSetPinCodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
