// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostTransactionSignReader is a Reader for the PostTransactionSign structure.
type PostTransactionSignReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTransactionSignReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostTransactionSignOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPostTransactionSignConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostTransactionSignOK creates a PostTransactionSignOK with default headers values
func NewPostTransactionSignOK() *PostTransactionSignOK {
	return &PostTransactionSignOK{}
}

/*PostTransactionSignOK handles this case with default header values.

success
*/
type PostTransactionSignOK struct {
	Payload *models.TransactionSignResponse
}

func (o *PostTransactionSignOK) Error() string {
	return fmt.Sprintf("[POST /transactionSign][%d] postTransactionSignOK  %+v", 200, o.Payload)
}

func (o *PostTransactionSignOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TransactionSignResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostTransactionSignConflict creates a PostTransactionSignConflict with default headers values
func NewPostTransactionSignConflict() *PostTransactionSignConflict {
	return &PostTransactionSignConflict{}
}

/*PostTransactionSignConflict handles this case with default header values.

error
*/
type PostTransactionSignConflict struct {
	Payload *models.HTTPErrorResponse
}

func (o *PostTransactionSignConflict) Error() string {
	return fmt.Sprintf("[POST /transactionSign][%d] postTransactionSignConflict  %+v", 409, o.Payload)
}

func (o *PostTransactionSignConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
