// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostBackupParams creates a new PostBackupParams object
// with the default values initialized.
func NewPostBackupParams() *PostBackupParams {

	return &PostBackupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostBackupParamsWithTimeout creates a new PostBackupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostBackupParamsWithTimeout(timeout time.Duration) *PostBackupParams {

	return &PostBackupParams{

		timeout: timeout,
	}
}

// NewPostBackupParamsWithContext creates a new PostBackupParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostBackupParamsWithContext(ctx context.Context) *PostBackupParams {

	return &PostBackupParams{

		Context: ctx,
	}
}

// NewPostBackupParamsWithHTTPClient creates a new PostBackupParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostBackupParamsWithHTTPClient(client *http.Client) *PostBackupParams {

	return &PostBackupParams{
		HTTPClient: client,
	}
}

/*PostBackupParams contains all the parameters to send to the API endpoint
for the post backup operation typically these are written to a http.Request
*/
type PostBackupParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post backup params
func (o *PostBackupParams) WithTimeout(timeout time.Duration) *PostBackupParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post backup params
func (o *PostBackupParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post backup params
func (o *PostBackupParams) WithContext(ctx context.Context) *PostBackupParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post backup params
func (o *PostBackupParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post backup params
func (o *PostBackupParams) WithHTTPClient(client *http.Client) *PostBackupParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post backup params
func (o *PostBackupParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostBackupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
