// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// NewPostGenerateAddressesParams creates a new PostGenerateAddressesParams object
// with the default values initialized.
func NewPostGenerateAddressesParams() *PostGenerateAddressesParams {
	var ()
	return &PostGenerateAddressesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostGenerateAddressesParamsWithTimeout creates a new PostGenerateAddressesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostGenerateAddressesParamsWithTimeout(timeout time.Duration) *PostGenerateAddressesParams {
	var ()
	return &PostGenerateAddressesParams{

		timeout: timeout,
	}
}

// NewPostGenerateAddressesParamsWithContext creates a new PostGenerateAddressesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostGenerateAddressesParamsWithContext(ctx context.Context) *PostGenerateAddressesParams {
	var ()
	return &PostGenerateAddressesParams{

		Context: ctx,
	}
}

// NewPostGenerateAddressesParamsWithHTTPClient creates a new PostGenerateAddressesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostGenerateAddressesParamsWithHTTPClient(client *http.Client) *PostGenerateAddressesParams {
	var ()
	return &PostGenerateAddressesParams{
		HTTPClient: client,
	}
}

/*PostGenerateAddressesParams contains all the parameters to send to the API endpoint
for the post generate addresses operation typically these are written to a http.Request
*/
type PostGenerateAddressesParams struct {

	/*GenerateAddressesRequest
	  GenerateAddressesRequest is request data for /api/v1/generate_addresses

	*/
	GenerateAddressesRequest *models.GenerateAddressesRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post generate addresses params
func (o *PostGenerateAddressesParams) WithTimeout(timeout time.Duration) *PostGenerateAddressesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post generate addresses params
func (o *PostGenerateAddressesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post generate addresses params
func (o *PostGenerateAddressesParams) WithContext(ctx context.Context) *PostGenerateAddressesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post generate addresses params
func (o *PostGenerateAddressesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post generate addresses params
func (o *PostGenerateAddressesParams) WithHTTPClient(client *http.Client) *PostGenerateAddressesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post generate addresses params
func (o *PostGenerateAddressesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGenerateAddressesRequest adds the generateAddressesRequest to the post generate addresses params
func (o *PostGenerateAddressesParams) WithGenerateAddressesRequest(generateAddressesRequest *models.GenerateAddressesRequest) *PostGenerateAddressesParams {
	o.SetGenerateAddressesRequest(generateAddressesRequest)
	return o
}

// SetGenerateAddressesRequest adds the generateAddressesRequest to the post generate addresses params
func (o *PostGenerateAddressesParams) SetGenerateAddressesRequest(generateAddressesRequest *models.GenerateAddressesRequest) {
	o.GenerateAddressesRequest = generateAddressesRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostGenerateAddressesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.GenerateAddressesRequest != nil {
		if err := r.SetBodyParam(o.GenerateAddressesRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
