// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostGenerateAddressesReader is a Reader for the PostGenerateAddresses structure.
type PostGenerateAddressesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostGenerateAddressesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostGenerateAddressesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPostGenerateAddressesConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostGenerateAddressesOK creates a PostGenerateAddressesOK with default headers values
func NewPostGenerateAddressesOK() *PostGenerateAddressesOK {
	return &PostGenerateAddressesOK{}
}

/*PostGenerateAddressesOK handles this case with default header values.

success
*/
type PostGenerateAddressesOK struct {
	Payload *models.GenerateAddressesResponse
}

func (o *PostGenerateAddressesOK) Error() string {
	return fmt.Sprintf("[POST /generateAddresses][%d] postGenerateAddressesOK  %+v", 200, o.Payload)
}

func (o *PostGenerateAddressesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenerateAddressesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostGenerateAddressesConflict creates a PostGenerateAddressesConflict with default headers values
func NewPostGenerateAddressesConflict() *PostGenerateAddressesConflict {
	return &PostGenerateAddressesConflict{}
}

/*PostGenerateAddressesConflict handles this case with default header values.

error
*/
type PostGenerateAddressesConflict struct {
	Payload *models.HTTPErrorResponse
}

func (o *PostGenerateAddressesConflict) Error() string {
	return fmt.Sprintf("[POST /generateAddresses][%d] postGenerateAddressesConflict  %+v", 409, o.Payload)
}

func (o *PostGenerateAddressesConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
