// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostSignMessageReader is a Reader for the PostSignMessage structure.
type PostSignMessageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSignMessageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostSignMessageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostSignMessageDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostSignMessageOK creates a PostSignMessageOK with default headers values
func NewPostSignMessageOK() *PostSignMessageOK {
	return &PostSignMessageOK{}
}

/*PostSignMessageOK handles this case with default header values.

successful operation
*/
type PostSignMessageOK struct {
	Payload *models.SignMessageResponse
}

func (o *PostSignMessageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SignMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostSignMessageDefault creates a PostSignMessageDefault with default headers values
func NewPostSignMessageDefault(code int) *PostSignMessageDefault {
	return &PostSignMessageDefault{
		_statusCode: code,
	}
}

/*PostSignMessageDefault handles this case with default header values.

error
*/
type PostSignMessageDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the post sign message default response
func (o *PostSignMessageDefault) Code() int {
	return o._statusCode
}

func (o *PostSignMessageDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *PostSignMessageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
