// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostIntermediateWordReader is a Reader for the PostIntermediateWord structure.
type PostIntermediateWordReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIntermediateWordReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostIntermediateWordOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostIntermediateWordDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostIntermediateWordOK creates a PostIntermediateWordOK with default headers values
func NewPostIntermediateWordOK() *PostIntermediateWordOK {
	return &PostIntermediateWordOK{}
}

/*PostIntermediateWordOK handles this case with default header values.

success
*/
type PostIntermediateWordOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PostIntermediateWordOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostIntermediateWordDefault creates a PostIntermediateWordDefault with default headers values
func NewPostIntermediateWordDefault(code int) *PostIntermediateWordDefault {
	return &PostIntermediateWordDefault{
		_statusCode: code,
	}
}

/*PostIntermediateWordDefault handles this case with default header values.

error
*/
type PostIntermediateWordDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the post intermediate word default response
func (o *PostIntermediateWordDefault) Code() int {
	return o._statusCode
}

func (o *PostIntermediateWordDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *PostIntermediateWordDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
