// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostIntermediatePassphraseReader is a Reader for the PostIntermediatePassphrase structure.
type PostIntermediatePassphraseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIntermediatePassphraseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostIntermediatePassphraseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostIntermediatePassphraseDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostIntermediatePassphraseOK creates a PostIntermediatePassphraseOK with default headers values
func NewPostIntermediatePassphraseOK() *PostIntermediatePassphraseOK {
	return &PostIntermediatePassphraseOK{}
}

/*PostIntermediatePassphraseOK handles this case with default header values.

success
*/
type PostIntermediatePassphraseOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PostIntermediatePassphraseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostIntermediatePassphraseDefault creates a PostIntermediatePassphraseDefault with default headers values
func NewPostIntermediatePassphraseDefault(code int) *PostIntermediatePassphraseDefault {
	return &PostIntermediatePassphraseDefault{
		_statusCode: code,
	}
}

/*PostIntermediatePassphraseDefault handles this case with default header values.

error
*/
type PostIntermediatePassphraseDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the post intermediate passphrase default response
func (o *PostIntermediatePassphraseDefault) Code() int {
	return o._statusCode
}

func (o *PostIntermediatePassphraseDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *PostIntermediatePassphraseDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
