// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostApplySettingsReader is a Reader for the PostApplySettings structure.
type PostApplySettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostApplySettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostApplySettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostApplySettingsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostApplySettingsOK creates a PostApplySettingsOK with default headers values
func NewPostApplySettingsOK() *PostApplySettingsOK {
	return &PostApplySettingsOK{}
}

/*PostApplySettingsOK handles this case with default header values.

success
*/
type PostApplySettingsOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PostApplySettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostApplySettingsDefault creates a PostApplySettingsDefault with default headers values
func NewPostApplySettingsDefault(code int) *PostApplySettingsDefault {
	return &PostApplySettingsDefault{
		_statusCode: code,
	}
}

/*PostApplySettingsDefault handles this case with default header values.

error
*/
type PostApplySettingsDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the post apply settings default response
func (o *PostApplySettingsDefault) Code() int {
	return o._statusCode
}

func (o *PostApplySettingsDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *PostApplySettingsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
