// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostApplySettingsReader is a Reader for the PostApplySettings structure.
type PostApplySettingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostApplySettingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostApplySettingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPostApplySettingsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostApplySettingsOK creates a PostApplySettingsOK with default headers values
func NewPostApplySettingsOK() *PostApplySettingsOK {
	return &PostApplySettingsOK{}
}

/*PostApplySettingsOK handles this case with default header values.

success
*/
type PostApplySettingsOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PostApplySettingsOK) Error() string {
	return fmt.Sprintf("[POST /applySettings][%d] postApplySettingsOK  %+v", 200, o.Payload)
}

func (o *PostApplySettingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostApplySettingsConflict creates a PostApplySettingsConflict with default headers values
func NewPostApplySettingsConflict() *PostApplySettingsConflict {
	return &PostApplySettingsConflict{}
}

/*PostApplySettingsConflict handles this case with default header values.

error
*/
type PostApplySettingsConflict struct {
	Payload *models.HTTPErrorResponse
}

func (o *PostApplySettingsConflict) Error() string {
	return fmt.Sprintf("[POST /applySettings][%d] postApplySettingsConflict  %+v", 409, o.Payload)
}

func (o *PostApplySettingsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
