// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostSignMessageReader is a Reader for the PostSignMessage structure.
type PostSignMessageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSignMessageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostSignMessageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPostSignMessageConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostSignMessageOK creates a PostSignMessageOK with default headers values
func NewPostSignMessageOK() *PostSignMessageOK {
	return &PostSignMessageOK{}
}

/*PostSignMessageOK handles this case with default header values.

successful operation
*/
type PostSignMessageOK struct {
	Payload *models.SignMessageResponse
}

func (o *PostSignMessageOK) Error() string {
	return fmt.Sprintf("[POST /signMessage][%d] postSignMessageOK  %+v", 200, o.Payload)
}

func (o *PostSignMessageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SignMessageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostSignMessageConflict creates a PostSignMessageConflict with default headers values
func NewPostSignMessageConflict() *PostSignMessageConflict {
	return &PostSignMessageConflict{}
}

/*PostSignMessageConflict handles this case with default header values.

error
*/
type PostSignMessageConflict struct {
	Payload *models.HTTPErrorResponse
}

func (o *PostSignMessageConflict) Error() string {
	return fmt.Sprintf("[POST /signMessage][%d] postSignMessageConflict  %+v", 409, o.Payload)
}

func (o *PostSignMessageConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
