// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostRecoveryReader is a Reader for the PostRecovery structure.
type PostRecoveryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRecoveryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRecoveryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPostRecoveryConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRecoveryOK creates a PostRecoveryOK with default headers values
func NewPostRecoveryOK() *PostRecoveryOK {
	return &PostRecoveryOK{}
}

/*PostRecoveryOK handles this case with default header values.

intermediate response
*/
type PostRecoveryOK struct {
	Payload *models.IntermediateResponse
}

func (o *PostRecoveryOK) Error() string {
	return fmt.Sprintf("[POST /recovery][%d] postRecoveryOK  %+v", 200, o.Payload)
}

func (o *PostRecoveryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IntermediateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRecoveryConflict creates a PostRecoveryConflict with default headers values
func NewPostRecoveryConflict() *PostRecoveryConflict {
	return &PostRecoveryConflict{}
}

/*PostRecoveryConflict handles this case with default header values.

error
*/
type PostRecoveryConflict struct {
	Payload *models.HTTPErrorResponse
}

func (o *PostRecoveryConflict) Error() string {
	return fmt.Sprintf("[POST /recovery][%d] postRecoveryConflict  %+v", 409, o.Payload)
}

func (o *PostRecoveryConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
