// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostIntermediatePassPhraseReader is a Reader for the PostIntermediatePassPhrase structure.
type PostIntermediatePassPhraseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostIntermediatePassPhraseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostIntermediatePassPhraseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostIntermediatePassPhraseDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostIntermediatePassPhraseOK creates a PostIntermediatePassPhraseOK with default headers values
func NewPostIntermediatePassPhraseOK() *PostIntermediatePassPhraseOK {
	return &PostIntermediatePassPhraseOK{}
}

/*PostIntermediatePassPhraseOK handles this case with default header values.

success
*/
type PostIntermediatePassPhraseOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PostIntermediatePassPhraseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostIntermediatePassPhraseDefault creates a PostIntermediatePassPhraseDefault with default headers values
func NewPostIntermediatePassPhraseDefault(code int) *PostIntermediatePassPhraseDefault {
	return &PostIntermediatePassPhraseDefault{
		_statusCode: code,
	}
}

/*PostIntermediatePassPhraseDefault handles this case with default header values.

error
*/
type PostIntermediatePassPhraseDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the post intermediate pass phrase default response
func (o *PostIntermediatePassPhraseDefault) Code() int {
	return o._statusCode
}

func (o *PostIntermediatePassPhraseDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *PostIntermediatePassPhraseDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
