// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostSetPinCodeReader is a Reader for the PostSetPinCode structure.
type PostSetPinCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSetPinCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostSetPinCodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostSetPinCodeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostSetPinCodeOK creates a PostSetPinCodeOK with default headers values
func NewPostSetPinCodeOK() *PostSetPinCodeOK {
	return &PostSetPinCodeOK{}
}

/*PostSetPinCodeOK handles this case with default header values.

success
*/
type PostSetPinCodeOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PostSetPinCodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostSetPinCodeDefault creates a PostSetPinCodeDefault with default headers values
func NewPostSetPinCodeDefault(code int) *PostSetPinCodeDefault {
	return &PostSetPinCodeDefault{
		_statusCode: code,
	}
}

/*PostSetPinCodeDefault handles this case with default header values.

error
*/
type PostSetPinCodeDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the post set pin code default response
func (o *PostSetPinCodeDefault) Code() int {
	return o._statusCode
}

func (o *PostSetPinCodeDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *PostSetPinCodeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
