// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// NewPostSetMnemonicParams creates a new PostSetMnemonicParams object
// with the default values initialized.
func NewPostSetMnemonicParams() *PostSetMnemonicParams {
	var ()
	return &PostSetMnemonicParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSetMnemonicParamsWithTimeout creates a new PostSetMnemonicParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSetMnemonicParamsWithTimeout(timeout time.Duration) *PostSetMnemonicParams {
	var ()
	return &PostSetMnemonicParams{

		timeout: timeout,
	}
}

// NewPostSetMnemonicParamsWithContext creates a new PostSetMnemonicParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSetMnemonicParamsWithContext(ctx context.Context) *PostSetMnemonicParams {
	var ()
	return &PostSetMnemonicParams{

		Context: ctx,
	}
}

// NewPostSetMnemonicParamsWithHTTPClient creates a new PostSetMnemonicParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSetMnemonicParamsWithHTTPClient(client *http.Client) *PostSetMnemonicParams {
	var ()
	return &PostSetMnemonicParams{
		HTTPClient: client,
	}
}

/*PostSetMnemonicParams contains all the parameters to send to the API endpoint
for the post set mnemonic operation typically these are written to a http.Request
*/
type PostSetMnemonicParams struct {

	/*SetMnemonicRequest
	  SetMnemonicRequest is request data for /api/v1/set_mnemonic

	*/
	SetMnemonicRequest *models.SetMnemonicRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post set mnemonic params
func (o *PostSetMnemonicParams) WithTimeout(timeout time.Duration) *PostSetMnemonicParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post set mnemonic params
func (o *PostSetMnemonicParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post set mnemonic params
func (o *PostSetMnemonicParams) WithContext(ctx context.Context) *PostSetMnemonicParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post set mnemonic params
func (o *PostSetMnemonicParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post set mnemonic params
func (o *PostSetMnemonicParams) WithHTTPClient(client *http.Client) *PostSetMnemonicParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post set mnemonic params
func (o *PostSetMnemonicParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSetMnemonicRequest adds the setMnemonicRequest to the post set mnemonic params
func (o *PostSetMnemonicParams) WithSetMnemonicRequest(setMnemonicRequest *models.SetMnemonicRequest) *PostSetMnemonicParams {
	o.SetSetMnemonicRequest(setMnemonicRequest)
	return o
}

// SetSetMnemonicRequest adds the setMnemonicRequest to the post set mnemonic params
func (o *PostSetMnemonicParams) SetSetMnemonicRequest(setMnemonicRequest *models.SetMnemonicRequest) {
	o.SetMnemonicRequest = setMnemonicRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostSetMnemonicParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.SetMnemonicRequest != nil {
		if err := r.SetBodyParam(o.SetMnemonicRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
