// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostIntermediateButtonParams creates a new PostIntermediateButtonParams object
// with the default values initialized.
func NewPostIntermediateButtonParams() *PostIntermediateButtonParams {

	return &PostIntermediateButtonParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostIntermediateButtonParamsWithTimeout creates a new PostIntermediateButtonParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostIntermediateButtonParamsWithTimeout(timeout time.Duration) *PostIntermediateButtonParams {

	return &PostIntermediateButtonParams{

		timeout: timeout,
	}
}

// NewPostIntermediateButtonParamsWithContext creates a new PostIntermediateButtonParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostIntermediateButtonParamsWithContext(ctx context.Context) *PostIntermediateButtonParams {

	return &PostIntermediateButtonParams{

		Context: ctx,
	}
}

// NewPostIntermediateButtonParamsWithHTTPClient creates a new PostIntermediateButtonParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostIntermediateButtonParamsWithHTTPClient(client *http.Client) *PostIntermediateButtonParams {

	return &PostIntermediateButtonParams{
		HTTPClient: client,
	}
}

/*PostIntermediateButtonParams contains all the parameters to send to the API endpoint
for the post intermediate button operation typically these are written to a http.Request
*/
type PostIntermediateButtonParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post intermediate button params
func (o *PostIntermediateButtonParams) WithTimeout(timeout time.Duration) *PostIntermediateButtonParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post intermediate button params
func (o *PostIntermediateButtonParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post intermediate button params
func (o *PostIntermediateButtonParams) WithContext(ctx context.Context) *PostIntermediateButtonParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post intermediate button params
func (o *PostIntermediateButtonParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post intermediate button params
func (o *PostIntermediateButtonParams) WithHTTPClient(client *http.Client) *PostIntermediateButtonParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post intermediate button params
func (o *PostIntermediateButtonParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PostIntermediateButtonParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
