// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// NewPostIntermediateWordParams creates a new PostIntermediateWordParams object
// with the default values initialized.
func NewPostIntermediateWordParams() *PostIntermediateWordParams {
	var ()
	return &PostIntermediateWordParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostIntermediateWordParamsWithTimeout creates a new PostIntermediateWordParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostIntermediateWordParamsWithTimeout(timeout time.Duration) *PostIntermediateWordParams {
	var ()
	return &PostIntermediateWordParams{

		timeout: timeout,
	}
}

// NewPostIntermediateWordParamsWithContext creates a new PostIntermediateWordParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostIntermediateWordParamsWithContext(ctx context.Context) *PostIntermediateWordParams {
	var ()
	return &PostIntermediateWordParams{

		Context: ctx,
	}
}

// NewPostIntermediateWordParamsWithHTTPClient creates a new PostIntermediateWordParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostIntermediateWordParamsWithHTTPClient(client *http.Client) *PostIntermediateWordParams {
	var ()
	return &PostIntermediateWordParams{
		HTTPClient: client,
	}
}

/*PostIntermediateWordParams contains all the parameters to send to the API endpoint
for the post intermediate word operation typically these are written to a http.Request
*/
type PostIntermediateWordParams struct {

	/*WordRequest
	  WordRequest is request data for /api/v1/intermediate/word

	*/
	WordRequest *models.WordRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post intermediate word params
func (o *PostIntermediateWordParams) WithTimeout(timeout time.Duration) *PostIntermediateWordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post intermediate word params
func (o *PostIntermediateWordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post intermediate word params
func (o *PostIntermediateWordParams) WithContext(ctx context.Context) *PostIntermediateWordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post intermediate word params
func (o *PostIntermediateWordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post intermediate word params
func (o *PostIntermediateWordParams) WithHTTPClient(client *http.Client) *PostIntermediateWordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post intermediate word params
func (o *PostIntermediateWordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWordRequest adds the wordRequest to the post intermediate word params
func (o *PostIntermediateWordParams) WithWordRequest(wordRequest *models.WordRequest) *PostIntermediateWordParams {
	o.SetWordRequest(wordRequest)
	return o
}

// SetWordRequest adds the wordRequest to the post intermediate word params
func (o *PostIntermediateWordParams) SetWordRequest(wordRequest *models.WordRequest) {
	o.WordRequest = wordRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostIntermediateWordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.WordRequest != nil {
		if err := r.SetBodyParam(o.WordRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
