// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostBackupReader is a Reader for the PostBackup structure.
type PostBackupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostBackupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostBackupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPostBackupConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostBackupOK creates a PostBackupOK with default headers values
func NewPostBackupOK() *PostBackupOK {
	return &PostBackupOK{}
}

/*PostBackupOK handles this case with default header values.

success
*/
type PostBackupOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PostBackupOK) Error() string {
	return fmt.Sprintf("[POST /backup][%d] postBackupOK  %+v", 200, o.Payload)
}

func (o *PostBackupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostBackupConflict creates a PostBackupConflict with default headers values
func NewPostBackupConflict() *PostBackupConflict {
	return &PostBackupConflict{}
}

/*PostBackupConflict handles this case with default header values.

error
*/
type PostBackupConflict struct {
	Payload *models.HTTPErrorResponse
}

func (o *PostBackupConflict) Error() string {
	return fmt.Sprintf("[POST /backup][%d] postBackupConflict  %+v", 409, o.Payload)
}

func (o *PostBackupConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
