// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PostRecoveryReader is a Reader for the PostRecovery structure.
type PostRecoveryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRecoveryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRecoveryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPostRecoveryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostRecoveryOK creates a PostRecoveryOK with default headers values
func NewPostRecoveryOK() *PostRecoveryOK {
	return &PostRecoveryOK{}
}

/*PostRecoveryOK handles this case with default header values.

intermediate response
*/
type PostRecoveryOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PostRecoveryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRecoveryDefault creates a PostRecoveryDefault with default headers values
func NewPostRecoveryDefault(code int) *PostRecoveryDefault {
	return &PostRecoveryDefault{
		_statusCode: code,
	}
}

/*PostRecoveryDefault handles this case with default header values.

error
*/
type PostRecoveryDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the post recovery default response
func (o *PostRecoveryDefault) Code() int {
	return o._statusCode
}

func (o *PostRecoveryDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *PostRecoveryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
