// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// NewPostIntermediatePassPhraseParams creates a new PostIntermediatePassPhraseParams object
// with the default values initialized.
func NewPostIntermediatePassPhraseParams() *PostIntermediatePassPhraseParams {
	var ()
	return &PostIntermediatePassPhraseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostIntermediatePassPhraseParamsWithTimeout creates a new PostIntermediatePassPhraseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostIntermediatePassPhraseParamsWithTimeout(timeout time.Duration) *PostIntermediatePassPhraseParams {
	var ()
	return &PostIntermediatePassPhraseParams{

		timeout: timeout,
	}
}

// NewPostIntermediatePassPhraseParamsWithContext creates a new PostIntermediatePassPhraseParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostIntermediatePassPhraseParamsWithContext(ctx context.Context) *PostIntermediatePassPhraseParams {
	var ()
	return &PostIntermediatePassPhraseParams{

		Context: ctx,
	}
}

// NewPostIntermediatePassPhraseParamsWithHTTPClient creates a new PostIntermediatePassPhraseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostIntermediatePassPhraseParamsWithHTTPClient(client *http.Client) *PostIntermediatePassPhraseParams {
	var ()
	return &PostIntermediatePassPhraseParams{
		HTTPClient: client,
	}
}

/*PostIntermediatePassPhraseParams contains all the parameters to send to the API endpoint
for the post intermediate pass phrase operation typically these are written to a http.Request
*/
type PostIntermediatePassPhraseParams struct {

	/*PassPhraseRequest
	  PassPhraseRequest is request data for /api/v1/intermediate/passPhrase

	*/
	PassPhraseRequest *models.PinMatrixRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post intermediate pass phrase params
func (o *PostIntermediatePassPhraseParams) WithTimeout(timeout time.Duration) *PostIntermediatePassPhraseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post intermediate pass phrase params
func (o *PostIntermediatePassPhraseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post intermediate pass phrase params
func (o *PostIntermediatePassPhraseParams) WithContext(ctx context.Context) *PostIntermediatePassPhraseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post intermediate pass phrase params
func (o *PostIntermediatePassPhraseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post intermediate pass phrase params
func (o *PostIntermediatePassPhraseParams) WithHTTPClient(client *http.Client) *PostIntermediatePassPhraseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post intermediate pass phrase params
func (o *PostIntermediatePassPhraseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPassPhraseRequest adds the passPhraseRequest to the post intermediate pass phrase params
func (o *PostIntermediatePassPhraseParams) WithPassPhraseRequest(passPhraseRequest *models.PinMatrixRequest) *PostIntermediatePassPhraseParams {
	o.SetPassPhraseRequest(passPhraseRequest)
	return o
}

// SetPassPhraseRequest adds the passPhraseRequest to the post intermediate pass phrase params
func (o *PostIntermediatePassPhraseParams) SetPassPhraseRequest(passPhraseRequest *models.PinMatrixRequest) {
	o.PassPhraseRequest = passPhraseRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostIntermediatePassPhraseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PassPhraseRequest != nil {
		if err := r.SetBodyParam(o.PassPhraseRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
