// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// NewPostSignMessageParams creates a new PostSignMessageParams object
// with the default values initialized.
func NewPostSignMessageParams() *PostSignMessageParams {
	var ()
	return &PostSignMessageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostSignMessageParamsWithTimeout creates a new PostSignMessageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostSignMessageParamsWithTimeout(timeout time.Duration) *PostSignMessageParams {
	var ()
	return &PostSignMessageParams{

		timeout: timeout,
	}
}

// NewPostSignMessageParamsWithContext creates a new PostSignMessageParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostSignMessageParamsWithContext(ctx context.Context) *PostSignMessageParams {
	var ()
	return &PostSignMessageParams{

		Context: ctx,
	}
}

// NewPostSignMessageParamsWithHTTPClient creates a new PostSignMessageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostSignMessageParamsWithHTTPClient(client *http.Client) *PostSignMessageParams {
	var ()
	return &PostSignMessageParams{
		HTTPClient: client,
	}
}

/*PostSignMessageParams contains all the parameters to send to the API endpoint
for the post sign message operation typically these are written to a http.Request
*/
type PostSignMessageParams struct {

	/*SignMessageRequest
	  SignMessageRequest is request data for /api/signMessage

	*/
	SignMessageRequest *models.SignMessageRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post sign message params
func (o *PostSignMessageParams) WithTimeout(timeout time.Duration) *PostSignMessageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post sign message params
func (o *PostSignMessageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post sign message params
func (o *PostSignMessageParams) WithContext(ctx context.Context) *PostSignMessageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post sign message params
func (o *PostSignMessageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post sign message params
func (o *PostSignMessageParams) WithHTTPClient(client *http.Client) *PostSignMessageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post sign message params
func (o *PostSignMessageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSignMessageRequest adds the signMessageRequest to the post sign message params
func (o *PostSignMessageParams) WithSignMessageRequest(signMessageRequest *models.SignMessageRequest) *PostSignMessageParams {
	o.SetSignMessageRequest(signMessageRequest)
	return o
}

// SetSignMessageRequest adds the signMessageRequest to the post sign message params
func (o *PostSignMessageParams) SetSignMessageRequest(signMessageRequest *models.SignMessageRequest) {
	o.SignMessageRequest = signMessageRequest
}

// WriteToRequest writes these params to a swagger request
func (o *PostSignMessageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.SignMessageRequest != nil {
		if err := r.SetBodyParam(o.SignMessageRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
