// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PutCancelReader is a Reader for the PutCancel structure.
type PutCancelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutCancelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutCancelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPutCancelConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutCancelOK creates a PutCancelOK with default headers values
func NewPutCancelOK() *PutCancelOK {
	return &PutCancelOK{}
}

/*PutCancelOK handles this case with default header values.

success
*/
type PutCancelOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PutCancelOK) Error() string {
	return fmt.Sprintf("[PUT /cancel][%d] putCancelOK  %+v", 200, o.Payload)
}

func (o *PutCancelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutCancelConflict creates a PutCancelConflict with default headers values
func NewPutCancelConflict() *PutCancelConflict {
	return &PutCancelConflict{}
}

/*PutCancelConflict handles this case with default header values.

error
*/
type PutCancelConflict struct {
	Payload *models.HTTPErrorResponse
}

func (o *PutCancelConflict) Error() string {
	return fmt.Sprintf("[PUT /cancel][%d] putCancelConflict  %+v", 409, o.Payload)
}

func (o *PutCancelConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
