// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutCancelParams creates a new PutCancelParams object
// with the default values initialized.
func NewPutCancelParams() *PutCancelParams {

	return &PutCancelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutCancelParamsWithTimeout creates a new PutCancelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutCancelParamsWithTimeout(timeout time.Duration) *PutCancelParams {

	return &PutCancelParams{

		timeout: timeout,
	}
}

// NewPutCancelParamsWithContext creates a new PutCancelParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutCancelParamsWithContext(ctx context.Context) *PutCancelParams {

	return &PutCancelParams{

		Context: ctx,
	}
}

// NewPutCancelParamsWithHTTPClient creates a new PutCancelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutCancelParamsWithHTTPClient(client *http.Client) *PutCancelParams {

	return &PutCancelParams{
		HTTPClient: client,
	}
}

/*PutCancelParams contains all the parameters to send to the API endpoint
for the put cancel operation typically these are written to a http.Request
*/
type PutCancelParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put cancel params
func (o *PutCancelParams) WithTimeout(timeout time.Duration) *PutCancelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put cancel params
func (o *PutCancelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put cancel params
func (o *PutCancelParams) WithContext(ctx context.Context) *PutCancelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put cancel params
func (o *PutCancelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put cancel params
func (o *PutCancelParams) WithHTTPClient(client *http.Client) *PutCancelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put cancel params
func (o *PutCancelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PutCancelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
