// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PutCancelReader is a Reader for the PutCancel structure.
type PutCancelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutCancelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutCancelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPutCancelDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutCancelOK creates a PutCancelOK with default headers values
func NewPutCancelOK() *PutCancelOK {
	return &PutCancelOK{}
}

/*PutCancelOK handles this case with default header values.

success
*/
type PutCancelOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PutCancelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutCancelDefault creates a PutCancelDefault with default headers values
func NewPutCancelDefault(code int) *PutCancelDefault {
	return &PutCancelDefault{
		_statusCode: code,
	}
}

/*PutCancelDefault handles this case with default header values.

error
*/
type PutCancelDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the put cancel default response
func (o *PutCancelDefault) Code() int {
	return o._statusCode
}

func (o *PutCancelDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *PutCancelDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
