// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PutFirmwareUpdateReader is a Reader for the PutFirmwareUpdate structure.
type PutFirmwareUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutFirmwareUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutFirmwareUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 409:
		result := NewPutFirmwareUpdateConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutFirmwareUpdateOK creates a PutFirmwareUpdateOK with default headers values
func NewPutFirmwareUpdateOK() *PutFirmwareUpdateOK {
	return &PutFirmwareUpdateOK{}
}

/*PutFirmwareUpdateOK handles this case with default header values.

successful operation
*/
type PutFirmwareUpdateOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PutFirmwareUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /firmwareUpdate][%d] putFirmwareUpdateOK  %+v", 200, o.Payload)
}

func (o *PutFirmwareUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutFirmwareUpdateConflict creates a PutFirmwareUpdateConflict with default headers values
func NewPutFirmwareUpdateConflict() *PutFirmwareUpdateConflict {
	return &PutFirmwareUpdateConflict{}
}

/*PutFirmwareUpdateConflict handles this case with default header values.

error
*/
type PutFirmwareUpdateConflict struct {
	Payload *models.HTTPErrorResponse
}

func (o *PutFirmwareUpdateConflict) Error() string {
	return fmt.Sprintf("[PUT /firmwareUpdate][%d] putFirmwareUpdateConflict  %+v", 409, o.Payload)
}

func (o *PutFirmwareUpdateConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
