// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/skycoin/hardware-wallet-daemon/src/models"
)

// PutFirmwareUpdateReader is a Reader for the PutFirmwareUpdate structure.
type PutFirmwareUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutFirmwareUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutFirmwareUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewPutFirmwareUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPutFirmwareUpdateOK creates a PutFirmwareUpdateOK with default headers values
func NewPutFirmwareUpdateOK() *PutFirmwareUpdateOK {
	return &PutFirmwareUpdateOK{}
}

/*PutFirmwareUpdateOK handles this case with default header values.

successful operation
*/
type PutFirmwareUpdateOK struct {
	Payload *models.HttpsuccessResponse
}

func (o *PutFirmwareUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HttpsuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPutFirmwareUpdateDefault creates a PutFirmwareUpdateDefault with default headers values
func NewPutFirmwareUpdateDefault(code int) *PutFirmwareUpdateDefault {
	return &PutFirmwareUpdateDefault{
		_statusCode: code,
	}
}

/*PutFirmwareUpdateDefault handles this case with default header values.

error
*/
type PutFirmwareUpdateDefault struct {
	_statusCode int

	Payload *models.HTTPErrorResponse
}

// Code gets the status code for the put firmware update default response
func (o *PutFirmwareUpdateDefault) Code() int {
	return o._statusCode
}

func (o *PutFirmwareUpdateDefault) Error() string {
	return o.Payload.Error.Message
}

func (o *PutFirmwareUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.HTTPErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
