// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ApplySettingsRequest apply settings request
// swagger:model ApplySettingsRequest
type ApplySettingsRequest struct {

	// label
	Label string `json:"label,omitempty"`

	// language
	Language string `json:"language,omitempty"`

	// use passphrase
	// Required: true
	UsePassphrase *bool `json:"use_passphrase"`
}

// Validate validates this apply settings request
func (m *ApplySettingsRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUsePassphrase(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApplySettingsRequest) validateUsePassphrase(formats strfmt.Registry) error {

	if err := validate.Required("use_passphrase", "body", m.UsePassphrase); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ApplySettingsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplySettingsRequest) UnmarshalBinary(b []byte) error {
	var res ApplySettingsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
