// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConfigurePinCodeRequest configure pin code request
// swagger:model ConfigurePinCodeRequest
type ConfigurePinCodeRequest struct {

	// remove pin
	// Required: true
	RemovePin *bool `json:"remove_pin"`
}

// Validate validates this configure pin code request
func (m *ConfigurePinCodeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRemovePin(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigurePinCodeRequest) validateRemovePin(formats strfmt.Registry) error {

	if err := validate.Required("remove_pin", "body", m.RemovePin); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConfigurePinCodeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigurePinCodeRequest) UnmarshalBinary(b []byte) error {
	var res ConfigurePinCodeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
