// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GenerateMnemonicRequest generate mnemonic request
// swagger:model GenerateMnemonicRequest
type GenerateMnemonicRequest struct {

	// use passphrase
	UsePassphrase bool `json:"use_passphrase,omitempty"`

	// word count
	// Required: true
	WordCount *int64 `json:"word_count"`
}

// Validate validates this generate mnemonic request
func (m *GenerateMnemonicRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWordCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GenerateMnemonicRequest) validateWordCount(formats strfmt.Registry) error {

	if err := validate.Required("word_count", "body", m.WordCount); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GenerateMnemonicRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GenerateMnemonicRequest) UnmarshalBinary(b []byte) error {
	var res GenerateMnemonicRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
