// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PassPhraseRequest pass phrase request
// swagger:model PassPhraseRequest
type PassPhraseRequest struct {

	// passphrase
	// Required: true
	Passphrase *string `json:"passphrase"`
}

// Validate validates this pass phrase request
func (m *PassPhraseRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePassphrase(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PassPhraseRequest) validatePassphrase(formats strfmt.Registry) error {

	if err := validate.Required("passphrase", "body", m.Passphrase); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PassPhraseRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PassPhraseRequest) UnmarshalBinary(b []byte) error {
	var res PassPhraseRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
