// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PinMatrixRequest pin matrix request
// swagger:model PinMatrixRequest
type PinMatrixRequest struct {

	// pin
	// Required: true
	Pin *string `json:"pin"`
}

// Validate validates this pin matrix request
func (m *PinMatrixRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePin(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PinMatrixRequest) validatePin(formats strfmt.Registry) error {

	if err := validate.Required("pin", "body", m.Pin); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PinMatrixRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PinMatrixRequest) UnmarshalBinary(b []byte) error {
	var res PinMatrixRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
