// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SignMessageRequest sign message request
// swagger:model SignMessageRequest
type SignMessageRequest struct {

	// address n
	// Required: true
	AddressN *int64 `json:"address_n"`

	// message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this sign message request
func (m *SignMessageRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddressN(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SignMessageRequest) validateAddressN(formats strfmt.Registry) error {

	if err := validate.Required("address_n", "body", m.AddressN); err != nil {
		return err
	}

	return nil
}

func (m *SignMessageRequest) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SignMessageRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignMessageRequest) UnmarshalBinary(b []byte) error {
	var res SignMessageRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
