// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TransactionOutput transaction output
// swagger:model TransactionOutput
type TransactionOutput struct {

	// address
	// Required: true
	Address *string `json:"address"`

	// address index
	// Required: true
	AddressIndex *int64 `json:"address_index"`

	// coins
	// Required: true
	Coins *string `json:"coins"`

	// hours
	// Required: true
	Hours *string `json:"hours"`
}

// Validate validates this transaction output
func (m *TransactionOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAddressIndex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCoins(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHours(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TransactionOutput) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *TransactionOutput) validateAddressIndex(formats strfmt.Registry) error {

	if err := validate.Required("address_index", "body", m.AddressIndex); err != nil {
		return err
	}

	return nil
}

func (m *TransactionOutput) validateCoins(formats strfmt.Registry) error {

	if err := validate.Required("coins", "body", m.Coins); err != nil {
		return err
	}

	return nil
}

func (m *TransactionOutput) validateHours(formats strfmt.Registry) error {

	if err := validate.Required("hours", "body", m.Hours); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TransactionOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransactionOutput) UnmarshalBinary(b []byte) error {
	var res TransactionOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
